In [13]:
import pandas as pd
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [16]:
import sys
!{sys.executable} -m pip install scikit-learn pandas numpy matplotlib scipy

Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [15]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC


In [17]:
from sklearn.ensemble import BaggingClassifier, AdaBoostClassifier, VotingClassifier


In [19]:
data = load_breast_cancer()

X = data.data
y = data.target

# Convert target values into required labels
# 0 -> Malignant, 1 -> Benign
target_mapping = {0: "Malignant", 1: "Benign"}

# Create DataFrame for better understanding (optional)
df = pd.DataFrame(X, columns=data.feature_names)
df['Target'] = y
df['Target_Name'] = df['Target'].map(target_mapping)

print("First 5 rows of dataset:")
print(df.head())

print("\nTarget Variable Mapping:")
print("0 -> Malignant")
print("1 -> Benign")

print("\nClass Distribution:")
print(df['Target_Name'].value_counts())

First 5 rows of dataset:
   mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst perimeter  worst area  worst 

In [21]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [23]:
print("\n" + "="*50)
print("BAGGING CLASSIFIER")
print("="*50)

bagging_model = BaggingClassifier(
    estimator=DecisionTreeClassifier(random_state=42),
    n_estimators=50,
    random_state=42
)

bagging_model.fit(X_train, y_train)
y_pred_bagging = bagging_model.predict(X_test)

print("Bagging Accuracy:", accuracy_score(y_test, y_pred_bagging))

# Convert predictions into required labels
bagging_pred_labels = [target_mapping[i] for i in y_pred_bagging]
actual_labels = [target_mapping[i] for i in y_test]

print("\nSample Bagging Predictions:")
for i in range(10):
    print(f"Actual: {actual_labels[i]}  |  Predicted: {bagging_pred_labels[i]}")

print("\nBagging Classification Report:")
print(classification_report(
    y_test, y_pred_bagging,
    target_names=["Malignant", "Benign"]
))

print("Bagging Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_bagging))


BAGGING CLASSIFIER
Bagging Accuracy: 0.9385964912280702

Sample Bagging Predictions:
Actual: Malignant  |  Predicted: Malignant
Actual: Benign  |  Predicted: Benign
Actual: Malignant  |  Predicted: Malignant
Actual: Benign  |  Predicted: Malignant
Actual: Malignant  |  Predicted: Malignant
Actual: Benign  |  Predicted: Benign
Actual: Benign  |  Predicted: Benign
Actual: Malignant  |  Predicted: Malignant
Actual: Malignant  |  Predicted: Malignant
Actual: Malignant  |  Predicted: Malignant

Bagging Classification Report:
              precision    recall  f1-score   support

   Malignant       0.93      0.90      0.92        42
      Benign       0.95      0.96      0.95        72

    accuracy                           0.94       114
   macro avg       0.94      0.93      0.93       114
weighted avg       0.94      0.94      0.94       114

Bagging Confusion Matrix:
[[38  4]
 [ 3 69]]


In [25]:
print("\n" + "="*50)
print("BOOSTING CLASSIFIER (AdaBoost)")
print("="*50)

boosting_model = AdaBoostClassifier(
    estimator=DecisionTreeClassifier(max_depth=1, random_state=42),
    n_estimators=50,
    learning_rate=1.0,
    random_state=42
)

boosting_model.fit(X_train, y_train)
y_pred_boosting = boosting_model.predict(X_test)

print("Boosting Accuracy:", accuracy_score(y_test, y_pred_boosting))

# Convert predictions into required labels
boosting_pred_labels = [target_mapping[i] for i in y_pred_boosting]

print("\nSample Boosting Predictions:")
for i in range(10):
    print(f"Actual: {actual_labels[i]}  |  Predicted: {boosting_pred_labels[i]}")

print("\nBoosting Classification Report:")
print(classification_report(
    y_test, y_pred_boosting,
    target_names=["Malignant", "Benign"]
))

print("Boosting Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_boosting))



BOOSTING CLASSIFIER (AdaBoost)


C:\ProgramData\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


Boosting Accuracy: 0.956140350877193

Sample Boosting Predictions:
Actual: Malignant  |  Predicted: Malignant
Actual: Benign  |  Predicted: Benign
Actual: Malignant  |  Predicted: Malignant
Actual: Benign  |  Predicted: Malignant
Actual: Malignant  |  Predicted: Malignant
Actual: Benign  |  Predicted: Benign
Actual: Benign  |  Predicted: Benign
Actual: Malignant  |  Predicted: Malignant
Actual: Malignant  |  Predicted: Malignant
Actual: Malignant  |  Predicted: Malignant

Boosting Classification Report:
              precision    recall  f1-score   support

   Malignant       0.97      0.90      0.94        42
      Benign       0.95      0.99      0.97        72

    accuracy                           0.96       114
   macro avg       0.96      0.95      0.95       114
weighted avg       0.96      0.96      0.96       114

Boosting Confusion Matrix:
[[38  4]
 [ 1 71]]


In [29]:
print("\n" + "="*50)
print("VOTING CLASSIFIER")
print("="*50)

# Define base classifiers
lr = LogisticRegression(max_iter=5000, random_state=42)
dt = DecisionTreeClassifier(random_state=42)
svm = SVC(probability=True, random_state=42)

# Hard Voting
voting_model = VotingClassifier(
    estimators=[
        ('lr', lr),
        ('dt', dt),
        ('svm', svm)
    ],
    voting='hard'
)

voting_model.fit(X_train, y_train)
y_pred_voting = voting_model.predict(X_test)

print("Voting Accuracy:", accuracy_score(y_test, y_pred_voting))

# Convert predictions into required labels
voting_pred_labels = [target_mapping[i] for i in y_pred_voting]

print("\nSample Voting Predictions:")
for i in range(10):
    print(f"Actual: {actual_labels[i]}  |  Predicted: {voting_pred_labels[i]}")

print("\nVoting Classification Report:")
print(classification_report(
    y_test, y_pred_voting,
    target_names=["Malignant", "Benign"]
))

print("Voting Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_voting))


VOTING CLASSIFIER
Voting Accuracy: 0.9649122807017544

Sample Voting Predictions:
Actual: Malignant  |  Predicted: Malignant
Actual: Benign  |  Predicted: Benign
Actual: Malignant  |  Predicted: Malignant
Actual: Benign  |  Predicted: Benign
Actual: Malignant  |  Predicted: Malignant
Actual: Benign  |  Predicted: Benign
Actual: Benign  |  Predicted: Benign
Actual: Malignant  |  Predicted: Malignant
Actual: Malignant  |  Predicted: Malignant
Actual: Malignant  |  Predicted: Malignant

Voting Classification Report:
              precision    recall  f1-score   support

   Malignant       0.97      0.93      0.95        42
      Benign       0.96      0.99      0.97        72

    accuracy                           0.96       114
   macro avg       0.97      0.96      0.96       114
weighted avg       0.97      0.96      0.96       114

Voting Confusion Matrix:
[[39  3]
 [ 1 71]]


In [31]:
print("\n" + "="*50)
print("FINAL ACCURACY COMPARISON")
print("="*50)

bag_acc = accuracy_score(y_test, y_pred_bagging)
boost_acc = accuracy_score(y_test, y_pred_boosting)
vote_acc = accuracy_score(y_test, y_pred_voting)

results = pd.DataFrame({
    'Model': ['Bagging', 'Boosting (AdaBoost)', 'Voting'],
    'Accuracy': [bag_acc, boost_acc, vote_acc]
})

print(results)

best_model = results.loc[results['Accuracy'].idxmax()]
print(f"\nBest Model: {best_model['Model']} with Accuracy = {best_model['Accuracy']:.4f}")


FINAL ACCURACY COMPARISON
                 Model  Accuracy
0              Bagging  0.938596
1  Boosting (AdaBoost)  0.956140
2               Voting  0.964912

Best Model: Voting with Accuracy = 0.9649
